- name: Configure mpv for Linux
  import_tasks: linux.yml
  when: ansible_distribution | lower is search('linux')

- name: Configure mpv for Mac
  import_tasks: mac.yml
  when: ansible_distribution | lower is search('mac')

