- hosts: '{{ host }}'
  become: True
  become_user: '{{ user }}'
  roles:
    - { role: zshrc, tags: zshrc }
    - { role: tmux, tags: tmux }
    - { role: neovim, tags: neovim }
    - { role: gitconfig, tags: gitconfig }
    - { role: inputrc, tags: inputrc }
    - { role: syncthing, tags: syncthing }

