- name: Configure qutebrowser on Linux
  import_tasks: linux.yml
  when: ansible_distribution | lower is search('linux')

- name: Configure qutebrowser on Mac
  import_tasks: mac.yml
  when: ansible_distribution | lower is search('mac')

