- name: Set configuration directory from XDG_CONFIG_HOME
  set_fact: 
    config_dir: '{{ ansible_env.XDG_CONFIG_HOME }}'
  register: set_config_dir_xdg
  ignore_errors: True

- name: Set configuration to default
  set_fact:
    config_dir: ~/.config/
  when: set_config_dir_xdg is failed

- name: Create configuration directory
  become: True
  become_user: '{{ user }}'
  file:
    path: '{{ config_dir }}'
    state: directory

