- name: Configure qutebrowser on Linux
  import_tasks: linux.yml
  when: ansible_distribution | lower is search('linux')

- name: Configure qutebrowser on Mac
  import_tasks: mac.yml
  when: ansible_distribution | lower is search('mac')

- name: Create ~/git/ directory (required for following git clone task)
  file:
    path: ~/git/
    state: directory

- name: Clone v0rn's fork of otsaloma's markdown-css repository (for GitHub Markdown previews)
  git:
    repo: https://github.com/v0rn/markdown-css.git
    dest: ~/git/markdown-css/

